# Renombrar este archivo como .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "TU_PROJECT_ID"
private_key_id = "TU_PRIVATE_KEY_ID"
private_key = "-----BEGIN PRIVATE KEY-----\nTU_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
client_email = "service-account@proyecto.iam.gserviceaccount.com"
client_id = "TU_CLIENT_ID"
token_uri = "https://oauth2.googleapis.com/token"

[google_sheet]
spreadsheet_id = "ID_DEL_GOOGLE_SHEET"


# ===============================
# USUARIOS DEL SISTEMA
# Cambiar hashes antes de usar.
# ===============================

[auth.users.admin]
name = "Administrador CTAR"
password_hash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9" # admin123
role = "admin"

[auth.users.ctar]
name = "Usuario CTAR"
password_hash = "317b852032103f64bee64760ea5a858590a65e0735251e56298db57b01dc749a" # ctar123
role = "ctar"

[auth.users.hospital]
name = "Usuario Hospital"
password_hash = "b936f714e474cd6ccc2843f2a5e9b1c6dd5a3c00fa5e1069b77fbb2d40524d3d" # hospital123
role = "hospital"

[auth.users.ifiscal]
name = "Inspector Fiscal"
password_hash = "59ef43e9b226cd24a2a592fb5e5c0f66b3cead13a6606c6bd8a587f71a5cf310" # if123
role = "if"
